### ISSUE TITLE
Will this work with paging and sorting as well?

### ISSUE THREAD

**Issue by tpdi** [tkaczmarzyk/specification-arg-resolver-example#1]
This looks very clean. Will it with paging and sorting as well?

**Comment by tkaczmarzyk** [comment]
Sure. I added an example of that to the sources.
1. You need to add a standard spring data resolver for pageables: https://github.com/tkaczmarzyk/specification-arg-resolver-example/blob/master/src/main/java/net/kaczmarzyk/example/Application.java#L26
2. Then you are ready to go: https://github.com/tkaczmarzyk/specification-arg-resolver-example/blob/master/src/main/java/net/kaczmarzyk/example/web/CustomerController.java#L66

**Comment by tkaczmarzyk** [comment]
BTW, if you didn't do that already, then also take a look on the readme of the lib, it includes some extra stuff not present in the original blogpost (like annotated specification interfaces)

**Comment by tpdi** [comment]
That was quick! Thanks, I will spend some time looking at this.
