### ISSUE TITLE
API find by firtstName not working

### ISSUE THREAD

**Issue by hendisantika** [tkaczmarzyk/specification-arg-resolver-example#2]
Nice repo.

I tried this example but I got this error : 
```
http://localhost:8080/customers?firstName=Homer


{
    "timestamp": "2018-01-13T01:48:46.220+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "Invoked method public abstract javax.persistence.criteria.Predicate org.springframework.data.jpa.domain.Specification.toPredicate(javax.persistence.criteria.Root,javax.persistence.criteria.CriteriaQuery,javax.persistence.criteria.CriteriaBuilder) is no accessor method!; nested exception is java.lang.IllegalArgumentException: Invoked method public abstract javax.persistence.criteria.Predicate org.springframework.data.jpa.domain.Specification.toPredicate(javax.persistence.criteria.Root,javax.persistence.criteria.CriteriaQuery,javax.persistence.criteria.CriteriaBuilder) is no accessor method!",
    "path": "/customers"
}
```

**Comment by hendisantika** [comment]
Sorry, I missed main App configuration.

Thanks

**Comment by munwarvh** [comment]
Hi,

Getting below error while hitting the request:
java.lang.IllegalArgumentException: Invoked method public abstract javax.persistence.criteria.Predicate org.springframework.data.jpa.domain.Specification.toPredicate(javax.persistence.criteria.Root,javax.persistence.criteria.CriteriaQuery,javax.persistence.criteria.CriteriaBuilder) is no accessor method!

Please help

**Comment by munwarvh** [comment]
> Sorry, I missed main App configuration.
> 
> Thanks

hi

**Comment by PradeepKeshavprakash** [comment]
> Sorry, I missed main App configuration.
> 
> Thanks

Can you please mention what you had missed in main app configuration?

**Comment by georgemavchun** [comment]
> Sorry, I missed main App configuration.
> 
> Thanks

Yes, please. Could you share the solution if possible?

**Comment by cpansegrouw** [comment]
add this to your spring config

```
	@Override
	public void addArgumentResolvers(
			List<HandlerMethodArgumentResolver> argumentResolvers) {
		argumentResolvers.add(new SpecificationArgumentResolver());
		argumentResolvers.add(new PageableHandlerMethodArgumentResolver());
	}
```
